apiVersion: apps/v1
kind: Deployment
metadata:
  name: files-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: files
  template:
    metadata:
      labels:
        app: files
    spec:
      containers:
        - name: files
          image: cardozoalan/files
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-key-chall
                  key: JWT_KEY
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-username-msusers-secret
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-password-msusers-secret
                  key: MONGO_PASSWORD
            - name: IAM_USER_KEY
              valueFrom:
                secretKeyRef:
                  name: access-key-id-aws
                  key: IAM_USER_KEY
            - name: IAM_USER_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-access-key-aws
                  key: IAM_USER_SECRET
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: bucket-name-aws
                  key: BUCKET_NAME
            - name: NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: namespace-aws
                  key: NAMESPACE
---
apiVersion: v1
kind: Service
metadata:
  name: files-srv
spec:
  selector:
    app: files
  ports:
    - name: files
      protocol: TCP
      port: 3000
      targetPort: 3000
