name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t cardozoalani/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push cardozoalani/auth
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.IAM_USER_KEY }}
           aws-secret-access-key: ${{ secrets.IAM_USER_SECRET }}
           aws-region: us-east-2
      - run: aws eks --region us-east-2 update-kubeconfig --name intree-01
      - run: kubectl rollout restart deployment auth-depl
