name: deploy-manifest

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.IAM_USER_KEY }}
           aws-secret-access-key: ${{ secrets.IAM_USER_SECRET }}
           aws-region: us-east-2
      - run: aws eks --region us-east-2 update-kubeconfig --name intree-01
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
